### ISSUE TITLE
[BUG] Section 5 BL-Touch maybe wrong Fan ducts link on thingiverse

### ISSUE THREAD

**Issue by feanor91** [Dtcreation/Firmware-Molise-Artillery#102]
### Describe the feature you want

Hello

I think you made a mistake on link you gives for this  : https://www.thingiverse.com/thing:3972011

You put it 2 times on line 141 and 144 but the probe offset are different 
NOZZLE_TO_PROBE_OFFSET { 28, -33, 0 } for 141
NOZZLE_TO_PROBE_OFFSET { 36, -38, 0 }  for 144

Same fan duct but 2 different offset... :)

Kind regards

**Comment by Dtcreation** [comment]
Hi,
The 2d is for BMG Wind
