### ISSUE TITLE
[BUG] Blocage d'impression + problème de température (400° ?)

### ISSUE THREAD

**Issue by Zazou49** [Dtcreation/Firmware-Molise-Artillery#107]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Bonjour,

J'ai déjà fait part de mes mésaventures sur le forum lesimprimantes3D arrivées il y a quelques semaines environ. 

Pour faire court, j'ai une genius, je suis en 2.4, après la MAJ, certaines impressions se bloquaient sans raison apparente. C'est-à-dire que la buse s'arrêtait en plein milieu d'une impression, le fil ne coulait plus, l'écran faisait toujours défiler les secondes. Je n'ai pas plus prêté attention que ça, je me suis dit que ça venait surement d'une erreur de slicage. 

J'ai ensuite fait une grosse pause d'impression. Puis il y a quelques semaines, j'ai lancé une impression de nuit, jusqu'au moment où j'ai été réveillé par une odeur de brûlée et une fumée blanche. L'impression avait encore bugguée, sauf que ça a fait d'important dégâts. Pour moi la buse a chauffé à 400°, ça a complétement fait fondre la chaussette en silicone, et ça a attaqué le bloc de chauffe.

Depuis je n'ai pas ré-imprimé. Difficile de savoir d'où vient l'erreur, firmware, slicage ? Mais je me dit qu'il peut-être opportun d'en parler ici. On m'a dit que normalement Marlin est censé couper l'impression s'il y a des anomalies de ce genre (température excessive, etc), mais ça ne s'est pas produit. Je ne sais pas si je peux aider, en donnant des fichiers logs du firmware ou quelque chose d'autre ? 

![IMG_4143 JPG da7f5eadf6f6839400eeb846f444569d](https://user-images.githubusercontent.com/89610869/148683594-c5f5289b-852a-4a6c-b62f-b6b3d905d7da.JPG)

### Version of Marlin Firmware

2.4

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

### Additional information & file uploads

Je n'ai pas touché à grand chose lors de la compilation, hormis mettre les drivers 2209 / BLtouch : [Configuration_adv.zip](https://github.com/Dtcreation/Firmware-Molise-Artillery/files/7835089/Configuration_adv.zip)

**Comment by SckyzO** [comment]
Salut @Zazou49 

Je pense que ton problème vient surtout du fait la sonde de température est / était défectueuse. 
Si elle est défectueuse, alors elle ne détecte pas la chaleur. J'ai déjà vu ce problème et cela fait exactement ce que tu décris.
