### ISSUE TITLE
[FR] (SKR20)

### ISSUE THREAD

**Issue by geg81** [Dtcreation/Firmware-Molise-Artillery#114]
### Are you looking for hardware support?

BTT SKR 2.0

### Describe the feature you want

Add the board to configuration.h

### Additional context

Hello!
I recently fried my TMC2100 drivers by "accidentally" disconnecting the case fan. So I decided to upgrade the whole board with a SKR 2.0 plus a full TMC2209 set, just to discover that there is little support for this board on the Sidewinder X1. 
I have already made some modifications to your firmware configuration but before starting a new fork I would like to know if you are interested in integrating the board. 

I also run the printer with an inductive probe PLUS the z_min endstop as a failsafe. The probe is the same z_min sensor type, I just got a replacement part and wired to the LED.

**Comment by bertenvdb** [comment]
I have almost the same setup and would love to see the SKR 2 suppprted!

**Comment by Jonweb08** [comment]
I'm also interested to use  the best Molise with SKR 2.0 !

**Comment by SckyzO** [comment]
Commit on branche marin-2.1.1. Can you try ?

**Comment by Jonweb08** [comment]
> Commit on branche marin-2.1.1. Can you try ?

Hi Tom, unfortunately the board is in delay or they lost my package and i can't help you, thanks for your commitment

**Comment by SckyzO** [comment]
No problem. I will wait :)

**Comment by SckyzO** [comment]
Work on marlin-2.1.1 branch. 
Coming soon on main branch :)
