### ISSUE TITLE
[BUG] BL TOUCH BAD FUNCTION MKS_SGENL_V1+TMC2209

### ISSUE THREAD

**Issue by JRRN** [Dtcreation/Firmware-Molise-Artillery#117]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

When try to do homming or start auto bed leveling the extruder go to center of the plate and start to do homming but when touch the plate don't stop and try to go down. 

Since I changed the board to MKS SGEN L 1.0 because the stock drivers, another bltouch and the board fused.

Video attached.

### Bug Timeline

Detected when change broken MKSGENL TO MKS_SGENL

### Expected behavior

Same functionality as broken MKSGENL

### Actual behavior

Z (Extruder) don't stop when bltouch detect the plate when homming or when start ABL.

### Steps to Reproduce

I tried enabling SENSHOME and disabled eith same results.
Settings all to false:

#define X_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Y_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MIN_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define X_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Y_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MAX_ENDSTOP_INVERTING false // Set to true to invert the logic of the endstop.
#define Z_MIN_PROBE_ENDSTOP_INVERTING false // Set to true to invert the logic of the probe.

With and without   #define HYBRID_THRESHOLD

No works.

### Version of Marlin Firmware

DT Creation Molise 3.0.3

### Printer model

Artillery Genius V1

### Electronics

MKS SGEN L 1.0 MKS TMC2209 UART BLTOUCH-Waggster the rest is stock

https://youtu.be/vSgcH2wjCwY
https://youtu.be/eF8Mqa2Y3oo

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Additional information & file uploads

[Marlin.zip](https://github.com/Dtcreation/Firmware-Molise-Artillery/files/8193388/Marlin.zip)

VIDEO: https://drive.google.com/file/d/1ikiUIOu7Amw6cRGQB8wAcVq5O6DNpKn5/view?usp=sharing

**Comment by JRRN** [comment]
Without SENSORLESS and without all DIAG Jumpers : https://drive.google.com/file/d/1pJBGwK09aosYsIEknd0X0BHWjLr1ESkR/view?usp=sharing

Without SENSORLESS and with JUMPERS: https://drive.google.com/file/d/1ikiUIOu7Amw6cRGQB8wAcVq5O6DNpKn5/view?usp=sharing
With SENSORLESS and with JUMPERS: anterior.https://drive.google.com/file/d/1ikiUIOu7Amw6cRGQB8wAcVq5O6DNpKn5/view?usp=sharing
With SENSORLESS and without JUMPERS, it goes to the end like the previous video but does not go down, just like the movement but without lowering the extruder and the bltouch does not work (https://drive.google.com/file/d/1ikiUIOu7Amw6cRGQB8wAcVq5O6DNpKn5/view?usp=sharing)

**Comment by SckyzO** [comment]
Hello, sorry for delay. do you still have the same issue ?

**Comment by JRRN** [comment]
> Hello, sorry for delay. do you still have the same issue ?

Yes, I have to switch off the machine and move manually the extruder to the 0,0 position.

**Comment by SckyzO** [comment]
Ok, so first, can you try to compil new version in master branch, and tell me if you still have this issue.

**Comment by JRRN** [comment]
Ok, @SckyzO I'll try tomorrow Sunday and get back to you with comments.

**Comment by JRRN** [comment]
@SckyzO  BLTouch don't detect the min position.

Error enabling bed leveling on start machine. Master code used.

Attached output log and configuration.

[output.log](https://github.com/Dtcreation/Firmware-Molise-Artillery/files/10046693/output.log)
[configguration.txt](https://github.com/Dtcreation/Firmware-Molise-Artillery/files/10046695/configguration.txt)

**Comment by SckyzO** [comment]
Did you try to do an Auto bed leveling after install Molise ? 
When you install Molise, first reset eeprom and do an ABL

**Comment by JRRN** [comment]
Yes, I have tried. But the Z goes down and doesn't stop, it hits the bed, even with the sensor activated. It seems that the signal that it has reached the bed is not interpreted by the firmware.

**Comment by JRRN** [comment]
https://mega.nz/file/O85lER6C#y7jbJvl0cy6gvGJxjx0frIymqQIzNY_ORii8UpY3LiY
[Configuration.txt](https://github.com/Dtcreation/Firmware-Molise-Artillery/files/10049340/Configuration.txt)

**Comment by JRRN** [comment]
@SckyzO Fixed I'm going to prepara the documentation but with my wired connections the problem is that some pins on MKS SGEN L changes:

![image](https://user-images.githubusercontent.com/8088427/206417416-f95a84c0-1a7b-4052-a78f-3090d38e5a76.png)

**Comment by JRRN** [comment]
![Pins](https://user-images.githubusercontent.com/8088427/206428444-4855668f-69a2-4561-a25c-f743f4f9050a.png)

Fixed Pins
