### ISSUE TITLE
Prise en charge de la fonction M73 de Marlin

### ISSUE THREAD

**Issue by SckyzO** [Dtcreation/Firmware-Molise-Artillery#12]
J'ai vu que PrusaSlicer avait une option M73 pour les imprimantes Prusa. Elle n'a pas compatible avec Molise. Lorsqu'on l'active, un message d'erreur dit que la commande M73 ... n'est pas prise en charge ... blablabla 😄  

https://marlinfw.org/docs/gcode/M073.html

![image](https://user-images.githubusercontent.com/683678/107825523-8b4aa380-6d83-11eb-879b-f046d2a298f5.png)

**Comment by larsan9** [comment]
![image](https://user-images.githubusercontent.com/70520760/107829554-4aa25880-6d8a-11eb-8530-a41b82be6b98.png)

**Comment by larsan9** [comment]
Creo que seria eso

**Comment by SckyzO** [comment]
Oh c'est uniquement pour les LCD ?
