### ISSUE TITLE
[FR] Est-il prévu une mise à jour vers MARLIN 2.1 ?

### ISSUE THREAD

**Issue by stargateSGU** [Dtcreation/Firmware-Molise-Artillery#121]
### Is your feature request related to a problem? Please describe.

J'utilise la version 3.0.3 avec ma sidewinder X1

### Are you looking for hardware support?

Sidewinder X1 avec SKR1.4 Bigtreetech

### Describe the feature you want

Est-il prévu une mise à jour pour la Sidewinder X1 avec marlin 2.1 ?

**Comment by SckyzO** [comment]
Passage sur marlin 2.1.1 directement. Je clôture
