### ISSUE TITLE
[FR] Est-il prévu une mise à jour vers MARLIN 2.1.1 ?

### ISSUE THREAD

**Issue by stargateSGU** [Dtcreation/Firmware-Molise-Artillery#122]
### Is your feature request related to a problem? Please describe.

Est-il prévu une mise à jour à base de MARLIN 2.1.1 pour la Sidewinder X1 ?

### Are you looking for hardware support?

SKR 1.4 TURBO

### Describe the feature you want

Firmware MOLISE a base de MARLIN 2.1.1 pour une Sidewinder X1

### Additional context

Merci

**Comment by SckyzO** [comment]
En cours 😊

**Comment by SckyzO** [comment]
Molise 4.0 based on Marlin 2.1.1
