### ISSUE TITLE
Infinite reboot sd card inserted 

### ISSUE THREAD

**Issue by cbboyd227** [Dtcreation/Firmware-Molise-Artillery#123]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello 
I am new to Marlin software this is my first
Custom code I have tried I am using molisa marlin
V2.1.
Everything works perfect the printer boots up 
Perfect and everything else perfect but with 
The sd card inserted the printer keeps rebooting 
I have looked up information for the last 2 weeks 
And tried everything.
Deactivated sd support fail 
Change the pin fail 
Tried different versions of firmware and when 
I do esteps it changes both extruder 1 and 2 
Where on the molisa I can change them individually 
I manufacture parts and need it to be spot on 
Everytime.
Can anyone please assist also this is my first 
Post and GITHUB feels confusing to me.
I can upload the whole code later when I have 
Access to the pc.
I have formatted the sd card fat32 and used 3 
Different ones and still the same problem.
I have no idea how to solve this problem.
Can anyone please assist.
I also found the code on GITHUB.
<https://github.com/Dtcreation/Firmware-Molise-Wanhao/blob/master/README.md>
Please see the attached code I used just changed 
The specs to my printer 

### Bug Timeline

2 weeks ago 

### Expected behavior

To read the sd card and be able to print 

### Actual behavior

Infinite reboot with sd card inserted 

### Steps to Reproduce

Load new firmware onto SD card 
Insert sd card 
Booting up 
Screen calibration 
Then reboot again non stop 
Remove sd card printer works perfectly 

### Version of Marlin Firmware

Molise 3

### Printer model

Wanhao D12/230

### Electronics

Stock machine 

### Host Software

SD Card (headless)

**Comment by SckyzO** [comment]
Hello, please open a case on Wanhao Molise Firmware. 
This repo is only for Artillery X1 : 

https://github.com/Dtcreation/Firmware-Molise-Wanhao/issues

I haven't a Wanhao to try this. And, I think support of wanhao will be stopped soon ....
