### ISSUE TITLE
[IT] Possibility to add a user friendly configuration on Molise 4.0 for BIGTREETECH Relay V1.2 and BTT UPS 24V V1.0

### ISSUE THREAD

**Issue by Jonweb08** [Dtcreation/Firmware-Molise-Artillery#136]
### Is your feature request related to a problem? Please describe.

NO it is a friendly request 

### Are you looking for hardware support?

Sidewinder x1
SKR board 

### Describe the feature you want

I know that it is an hard job the coding, I'm mechanical old guys with very very few knowledge in electronic.
It could be a good feature to add the functionality of BIGTREETECH Relay V1.2 and BTT UPS 24V V1.0 on our Molise, means the part of the code to activate it.

It is only a request not a bug

**Comment by SckyzO** [comment]
To do this, you need to  uncomment this lines :

https://github.com/Dtcreation/Firmware-Molise-Artillery/blob/master/Marlin/Configuration.h#L684
https://github.com/Dtcreation/Firmware-Molise-Artillery/blob/master/Marlin/Configuration.h#L685

And line : https://github.com/Dtcreation/Firmware-Molise-Artillery/blob/master/Marlin/Configuration.h#L691
- set PSU_ACTIVE_STATE : LOW to HIGH

- BTT UPS 24V V1.0 support : 
https://github.com/Dtcreation/Firmware-Molise-Artillery/blob/master/Marlin/Configuration_adv.h#L1630

I think it will work
