### ISSUE TITLE
[BUG] Hauteur de Z incorrecte lors de l'impression

### ISSUE THREAD

**Issue by Pi3rrick** [Dtcreation/Firmware-Molise-Artillery#142]
### Did you test the latest Molise code ?

Yes, and the problem still exists.

### Bug Description

Même après le réglage du Z-Offset la buse se place a environ 10mm au dessus du plateau et affiche à l'écran la hauteur de couche attendue (Par exemple 0.2) alors qu'elle est réellement bien plus haute. 
Le bed levelling et le home fonctionnent même si j'ai pu observer des "probe failing" car la position initiale du bltouch était trop haute et ne descendait pas assez pour rentrer en contact avec le bed. (Problème aléatoire)  

### Bug Timeline

New bug

### Version of Molise or Marlin Firmware

Release 4.0

### Printer model

X1

### Electronics

SKR 2 Rev A

### Add-ons

TMC 2209 + Tete Hemera

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by Black-Widow** [comment]
Bonjour, j'ai le meme soucis

**Comment by SckyzO** [comment]
Bonjour, 

Désolé de la réponse tardive j'étais pris sur d'autres projets. 

As tu résolu ton problème ?
