### ISSUE TITLE
Changing LED while printing

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-Artillery#23]
A small improvements suggestion:
- original firmware allows to change the LED while printing
- add 3 more colors by combining R+V, R+B, B+V
- M150 allows to fade blue, green but not red, configuration bug?

Based on Molise 1.3.0

Thanks for the huge work!

**Comment by eiffel31** [comment]
Sorry, it is possible to modify LED setting while printing!
I missed the menu...

**Comment by Dtcreation** [comment]
okay 👍
