### ISSUE TITLE
Heated bed for homing

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-Artillery#24]
Heating the bed before every homing is sometimes not practical at all.
Anoyances:
- delay
- hot surface

Could be better if the bed temperature could be selected (some preset values and adjustments buttons) at each homing order instead of automatic heating to 50°C.

Probe leveling for example has no interest into bed heating, extruder heating is more appropriate.

Thanks!

**Comment by Dtcreation** [comment]
Hi,

This feature was in high demand.
I will study the feedback

**Comment by SckyzO** [comment]
Suggest to add this in option in Molise. I use this feature because when the bed heats up, the surface moves a little. Which makes the BLtouch even more precise.

**Comment by eiffel31** [comment]
Hi,
Right, when the bed heats up, it will move and the shape of the surface will change. I'll try to make things more clear:

The bed heating value has to be user configurable for:
- manual bed leveling
- automatic bed leveling
- homing for print

The nozzle heating value has to be user configurable for:
- probe offset calibration
- homing for print

This issue should be in TFT, not in firmware. But TFT is provided in firmware...

**Comment by SckyzO** [comment]
Hi, 
Ah ok ... I understand :)
