### ISSUE TITLE
Configuration files missing

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-Artillery#25]
I spent a full day to make the bl touch working with pre-compiled firmware handling the bl touch. I was ready to give up, convinced that my bl touch was defective, when I found the problem: in the pre-compiled firmware, the bl-touch is configured to be plugged on Z+ and I plug it in Z- as Guero Loco.

This point is not detailed in all the documents I read.

If the configuration file is available within the zip file containing the pre-compiled firmware, at least everyone can check the settings made.

Thanks

**Comment by Dtcreation** [comment]
Hi,

I will specify that on the readme

Thanks
