### ISSUE TITLE
Wrong printing speed

### ISSUE THREAD

**Issue by eiffel31** [Dtcreation/Firmware-Molise-Artillery#27]
The printing speed seems to be higher than expected.

Prevision from Prusaslicer: 30h

Filament was not melted enough, so I increased the temperature and slow down the printing speed to 90% most of the time and 80% on some parts, some slower tests. Total print time: 28h45'. According to the reduced print speed and initial prevision, I expected at least 35h of print time.

28h45' is the printed value, it is correct according to the wall clock.

Is Prusaslicer so pessimistic?

**Comment by SckyzO** [comment]
The slicer only provides an estimate ... Not a molise bug.

**Comment by SckyzO** [comment]
Just, for information, do you try same model, same settings on Cura, S3D and Prusa ? 3 Slicer, same settings, 3 différents time for the same model for me :-)

**Comment by eiffel31** [comment]
Do you mean opening the same gcode file gives these 3 different times?

**Comment by SckyzO** [comment]
Yes. you can try. Each Slicer works differently. 
And all they do is estimate the time. It is not something "stable". In addition, each Slicer has its own way of working (movement, optimization, etc.)

**Comment by Dtcreation** [comment]
Hi,

Not a firmware issue, slicer issue
