### ISSUE TITLE
Feature request : Smart Sensor

### ISSUE THREAD

**Issue by jpreculeau** [Dtcreation/Firmware-Molise-Artillery#32]
Hello,

Is it possible to add an option for the BTT Smart Sensor (on the mainboad to use with octoprint) ?
Doc of the bidule : https://github.com/bigtreetech/smart-filament-detection-module/tree/master/manual

Thanks for the great work.

**Comment by Dtcreation** [comment]
Bonjour,

Ce capteur a des réglages trop spécifiques qui rentrent en conflit avec le capteur d'origine, je ne peux donc pas le rajouter en standard 🙇‍♂️

**Comment by jpreculeau** [comment]
Ok je comprends. du coup pour l'utiliser il vaut mieux que je m'abstienne d'activer le capteur dans les sections de configuration et directement faire les modifs dans marlin ou dois je faire quelque chose en plus s'il y a des spécificités avec les ajouts de ton firmware ?
