### ISSUE TITLE
Runout sensor alternative pin

### ISSUE THREAD

**Issue by amoutiers** [Dtcreation/Firmware-Molise-Artillery#57]
Hello David,

You said in the readme, that we can plug the runout sensor on the motherboard
> - Removal of the runout filament sensor on the motherboard for compatibility with Octoprint and SD reader on the motherboard (Option)

Do you have the schematics for that ?

Best regards
Antoine

J'ai écris en anglais comme c'est de coutume sur Github ;-)

**Comment by Dtcreation** [comment]
Hello,

Il faut l brancher sur le X+

**Comment by amoutiers** [comment]
Merci, j'ai fait une PR pour le coup #73
