### ISSUE TITLE
#define MKSGENL_TFT

### ISSUE THREAD

**Issue by AndroSteph** [Dtcreation/Firmware-Molise-Artillery#58]
Bonjour/Bonsoir David,

Juste pour signaler que dans la version 1.4.0 (fichier avec les sources) l'option "#define MKSGENL_TFT" est présente avec les deux "//", donc "//#define MKSGENL_TFT", étant donné que je ne sais pas si dans les fichier précompilés "xxxx.hex" cette option est bien activée et comme j'ai modifié le câblage de mon écran, je me suis compilé ma version pour mon prochain flashage.

Ma question y-a-t 'il une raison pour avoir laissé les "//" dans les sources pour cette option ?

Merci,
Stéphane

**Comment by Dtcreation** [comment]
Bonjour,

Juste un oubli  !
