### ISSUE TITLE
[FR] Add MeatPack support

### ISSUE THREAD

**Issue by jgason** [Dtcreation/Firmware-Molise-Artillery#6]
Hi, 

It would be really cool if you could add the support for the MeatPack compression for Octoprint (https://github.com/scottmudge/OctoPrint-MeatPack#firmware-with-meatpack-support)

Seems like the nightly builds of Marlin has it already so if luck is on our side it would be easy to do

**Comment by Dtcreation** [comment]
Hi,

I only use Marlin Official release, if Meatpack is the next release, il will be in Molise.

There are a lot of bugs in Marlin nightly builds

**Comment by Dtcreation** [comment]
Hi,

You can now activate it on Molise !!

**Comment by jgason** [comment]
Bonjour,

 

y-a-t’il une ligne a decommenter dans la compilation ou est-ce dedans par defaut ?

 

Bien á vous

 

Jean-Luc Gason

 

De : Molise <notifications@github.com> 
Envoyé : 22 February 2021 13:31
À : Dtcreation/Firmware-Molise-Artillery <Firmware-Molise-Artillery@noreply.github.com>
Cc : jgason <jeanluc@dontblink.be>; Author <author@noreply.github.com>
Objet : Re: [Dtcreation/Firmware-Molise-Artillery] [FR] Add MeatPack support (#6)

 

Hi,

You can now activate it on Molise !!
