### ISSUE TITLE
X/Y homing failing 5% of the time due to noise

### ISSUE THREAD

**Issue by matthieut59** [Dtcreation/Firmware-Molise-Artillery#79]
Hello

I checked a lot of firmware based on marlin for sidewinder X1 (and the most popular ones, including Waggster etc.), and all of them have this feature activate : 
#define ENDSTOP_NOISE_THRESHOLD 2

It's not activated in Molise, and it's clearly impacting X/Y homing with random issues (not common but it happens)

I would suggest to activate it by default in molise.

Matt

**Comment by rth630** [comment]
I think this have to do with sensorless Homing of the TMC. There it must be disabled.

**Comment by Dtcreation** [comment]
Hi,
Anabled again in the last version 2.0
