### ISSUE TITLE
Changes on config for MKS SGEN L v2

### ISSUE THREAD

**Issue by rth630** [Dtcreation/Firmware-Molise-Artillery#80]
Can you take a look of the config from the MKS SGEN L v2 for the next build? Some changes are necessary : E0_AUTO_FAN_PIN -> FAN2_PIN, Filamentsensor on X+ -> FIL_RUNOUT_PIN P1_28 (2 is for AUX1), if no waggster-mod for RGB-LED with the extra pins P1_19 - P1_21 of this board enable only RGB_LED (pins are defined in PINS) so you can put the white connector with the brown cables direct. (wrong order of the cables, have to change the config in PINS or change two cables). Also with molise i dont  
see the onboard-SD form PC over USB (for send firmware to the bord) with stock marlin-bugfix i see it.

**Comment by Dtcreation** [comment]
Hi,
Changes done in next Molise 2.0
