### ISSUE TITLE
Problem with line 317 / MKS SGEN L V2

### ISSUE THREAD

**Issue by mfjnext** [Dtcreation/Firmware-Molise-Artillery#84]
Dear All,
There is a problem with the 317 line and the MKS SGEN L V2.0 cards.
End of line creates errors when compile : 1151 // MKS GEN L V2
Not knowing what it's for, I deleted it.

<img width="499" alt="2021-05-11 21_27_21-Configuration h - Firmware-Molise-Artillery-master 2 0 - Visual Studio Code" src="https://user-images.githubusercontent.com/24639254/117874157-f16e9600-b2a0-11eb-9eef-7732d800f57f.png">

<img width="744" alt="2021-05-11 21_33_49-Configuration h - Firmware-Molise-Artillery-master 2 0 - Visual Studio Code" src="https://user-images.githubusercontent.com/24639254/117874172-f5021d00-b2a0-11eb-8a1f-0120c45e9f10.png">

**Comment by Dtcreation** [comment]
Hi,

Solved in last Release

**Comment by mfjnext** [comment]
Thanks
