### ISSUE TITLE
M600 : gros dépot de filament 

### ISSUE THREAD

**Issue by Zazou89** [Dtcreation/Firmware-Molise-Artillery#86]
### Description

J'utilise PrusaSlicer pour mes impressions, leur logiciel permet de faire un M600. Seulement, après le changement de couleur, l'impression reprend, la buse se place à la dernière position connue et extrude du fil (un gros paté) avant de continuer son impression. 

Je pensais que le soucis venait de PruaSlicer mais apparement non, le développeur me dit que ça vient du firmware : https://github.com/prusa3d/PrusaSlicer/issues/6523

### Steps to Reproduce

1. Ajouter un M600 dans l'impression
2. Changer la couleur
3. Attendre le résultat

**Expected behavior:** je ne sais pas trop, une sorte de purge à côté de l'impression.

**Actual behavior:** un gros dépôt de filament sur l'impression

#### Additional Information

N/A

**Comment by Guilouz** [comment]
Cela a été corrigé avec les dernières releases firmwares écran BTT et Marlin.
