### ISSUE TITLE
[BUG] BLTOUCH issue

### ISSUE THREAD

**Issue by batreseau** [Dtcreation/Firmware-Molise-Artillery#97]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

Hello, I flashed my printer (artillery SX1 v4) and my bltouch not working well now.

**When i turn on my printer, BLTOUCH work as expected by releasing pin two times.** 

After screen loading, i have a popup regarding bltouch activation issue.
When i try to use BLTOUCH, nothing happen.

I tried Normal wiring (Guero Loco) and Waggster mod with two different BLTOUCHs

### Bug Timeline

New

### Expected behavior

BLTOUCH work for bed leveling / homing / print

### Actual behavior

BLTOUCH not woring for bed leveling / homing / print

### Steps to Reproduce

1. Download GIT folder
2. Compile Molise with following parameters:
![image](https://user-images.githubusercontent.com/5255313/139260164-8eb81885-acd0-427f-b6be-1e59b81633eb.png)
![image](https://user-images.githubusercontent.com/5255313/139260106-c6ccb8e0-2089-47b0-9c77-7ce419998c26.png)

3. Retrieve HEX file from .pio\build\mega2560
4. Open printer and disconnect screen
5. Flash printer using Prusa Slicer
6. Reconnect screen

### Version of Marlin Firmware

Marlin 2.0.8

### Printer model

Artillery Sidewinder X1 v4

### Electronics

Stock

### Add-ons

None

### Bed Leveling

ABL Linear grid

### Your Slicer

Cura

**Comment by Dtcreation** [comment]
Hi,
Can you try with the last release ?

**Comment by SckyzO** [comment]
Pas de réponse, clôture du ticket
