### ISSUE TITLE
[BUG] Hotends neopixel led for TouchMi don't light on

### ISSUE THREAD

**Issue by capitainekurck** [Dtcreation/Firmware-Molise-Artillery#98]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

I can light on the led through the menu or it light on when i do a bed PID with GCode but it don't light and change colour  while normal print or while normal operation

### Expected behavior

I expect the led light on and change colour while nozzle heat or while printing 

### Actual behavior

it don't light

### Steps to Reproduce

just printing

### Version of Marlin Firmware

last molise firmware (motherboard and TFT)

### Printer model

Xwinder X1

### Your Slicer

Cura

**Comment by Dtcreation** [comment]
hi,

Do you print from SD card or Octoprint ?

**Comment by SckyzO** [comment]
Pas de réponse, je clôture
